name: around
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.4.3
  intl: ^0.18.0
  google_fonts: ^4.0.3
  omni_datetime_picker: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_gen_runner: ^5.1.0+1
  freezed: ^2.1.0+1

flutter:
  assets:
    - assets/
    - assets/covers/
  uses-material-design: true


