name: around
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.4.3
  intl: ^0.18.0
  google_fonts: ^4.0.3
  omni_datetime_picker: ^0.1.4
  http: ^0.13.5
  flutter_typeahead: ^4.3.1
  autocomplete_textfield: ^2.0.1
  hive: ^2.2.3
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_gen_runner: ^5.1.0+1
  freezed: ^2.1.0+1

#  flutter_launcher_icons: 0.11.0
#  flutter_launcher_name: ^0.0.1
  #  flutter_launcher_name: # flutter pub get

  # flutter pub run flutter_launcher_icons:main
  # "WARNING: Icons with alpha channel are not allowed in the Apple App Store.
  # Set "remove_alpha_ios: true" to remove it."
flutter_icons:
  ios: true
  android: "ic_launcher"
  image_path: "assets/app_icon.png"

flutter:
  assets:
    - assets/
    - assets/covers/
  uses-material-design: true


